name: Github metrics

on:
    workflow_dispatch: # for manual workflow trigger
    schedule:
        - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  filename: metrics.svg
                  token: ${{ secrets.GH_TOKEN }}
                  base: header, activity, community, repositories, metadata
                  config_timezone: America/Chicago
                  plugin_wakatime: yes
                  plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
                  plugin_wakatime_limit: 4
                  plugin_wakatime_days: 30
                  plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
                  plugin_wakatime_url: ${{ secrets.API_BASE_URL }}
                  plugin_wakatime_user: .user.login
                  plugin_achievements: yes
                  plugin_achievements_display: detailed
                  plugin_achievements_secrets: yes
                  plugin_achievements_threshold: C
                  user: phamleduy04
                  template: classic
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: full-year
                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_analysis_timeout_repositories: 7.5
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_limit: 8
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%
                  plugin_languages_indepth: true
